### ISSUE TITLE
Cannot call method onMsg

### ISSUE THREAD

**Issue by aceArt-GmbH** [LivePersonInc/dropwizard-websockets#33]
Randomly I seem to get following error

```
ERROR [2023-09-07 08:38:58,147] com.myProject.websockets.LiveWebsocketResource: websocket error: Cannot call method public void com.myProject.websockets.LiveWebsocketResource#onMsg(java.lang.Object, java.lang.String) with args: [org.eclips
e.jetty.websocket.jsr356.JsrSession, java.lang.String]
ERROR [2023-09-07 08:41:00,371] org.hibernate.engine.jdbc.spi.SqlExceptionHelper: (conn=2269) Lock wait timeout exceeded; try restarting transaction
ERROR [2023-09-07 08:41:00,375] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 6324d703a0d6b8fa
```

I can't reproduce locally though. Even if `onMsg` is accepting only `javax.websocket.Session` it occurs.
This error seems to lock some of my DB tables.

Maybe this is related to me using dropwizard2.1

**Comment by aceArt-GmbH** [comment]
So, I get the same error
```
ERROR [2023-09-12 06:30:54,329] com.myProject.websockets.LiveWebsocketResource: websocket error: Cannot call method public void com.myProject.websockets.LiveWebsocketResource#onMsg(java.lang.Object, java.lang.String) with args: [org.eclipse.jetty.websocket.jsr356.JsrSession, java.lang.String]
```
with dropwizard 1.3.29 and dropwizard-websockets 1.3.14 but without the table lock

**Comment by aceArt-GmbH** [comment]
```
java.lang.RuntimeException: Cannot call method public void com.myProject.websockets.LiveWebsocketResource#onMsg(java.lang.Object, java.lang.String) with args: [org.eclipse.jetty.websocket.jsr356.JsrSession, java.lang.String]
        at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.unwrapRuntimeException(CallableMethod.java:93)
        at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:75)
        at org.eclipse.jetty.websocket.jsr356.annotations.OnMessageTextCallable.call(OnMessageTextCallable.java:63)
        at org.eclipse.jetty.websocket.jsr356.annotations.JsrEvents.callText(JsrEvents.java:197)
        at org.eclipse.jetty.websocket.jsr356.endpoints.JsrAnnotatedEventDriver.onTextMessage(JsrAnnotatedEventDriver.java:375)
        at io.dropwizard.metrics.jetty9.websockets.annotated.InstJsrAnnotatedEventDriver.onTextMessage(InstJsrAnnotatedEventDriver.java:49)
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:67)
        at org.eclipse.jetty.websocket.jsr356.endpoints.JsrAnnotatedEventDriver.onTextFrame(JsrAnnotatedEventDriver.java:357)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:152)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:326)
        at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextIncomingFrame(AbstractExtension.java:148)
        at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:111)
        at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.forwardIncoming(CompressExtension.java:169)
        at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.incomingFrame(PerMessageDeflateExtension.java:90)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:202)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:225)
        at org.eclipse.jetty.websocket.common.Parser.parseSingleFrame(Parser.java:259)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:459)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:440)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException
        at com.myProject.websockets.LiveWebsocketResource.onMsg(LiveWebsocketResource.java:275)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
        ... 29 more
ERROR  [10:58:31.511] [dw-25] c.r.p.w.LiveWebsocketResource -  websocket error: Cannot call method public void com.myProject.websockets.LiveWebsocketResource#onMsg(java.lang.Object, java.lang.String) with args: [org.eclipse.jetty.websocket.jsr356.JsrSession, java.lang.String] 
```

When throwing an exception, it seems to trigger the same error (not sure if all occurrences of the error are from an exception).

I think because of the thrown exception, the database session never got unbound which does not play nice with newer Dropwizard (https://github.com/dropwizard/dropwizard/pull/2913) and therefore the database lock.
So catching the exceptions should resolve my problem
